# config/config.yaml
# note the use of forward slashes for file paths
# file types need to stay the same: do not change from xlxs to csv and vice-versa

box_repo:
  # Full path to your local Box repo clone
  root: "C:/Users/sruddy1/Box"
  pell_dir: "C:/Users/sruddy1/Box/Office of Decision Support Analyst Projects/ATI Kessler/Fall 2025 Pell Reporting"
  pell_file: "Pell Recipients by Academic Term or Year 25-11-26.xlsx"
  retention_dir: "C:/Users/sruddy1/Box/Inst Res Collab/Tableau Server Data Sources/Retention"
  retention_file: "Undergraduate Retention and Graduation.csv"
  enrollment_dir: "C:/Users/sruddy1/Box/Inst Res Collab/Tableau Server Data Sources/Census Date Enrollment"
  enrollment_file: "Census Date Enrollment (Decision Support Curated).csv"
  results_dir: "C:/Users/sruddy1/Box/Office of Decision Support Analyst Projects/ATI Kessler/Fall 2025 Pell Reporting/Results/Fall 2025"
  results_file: "University of Dayton 2025 ATI Prelim.xlsx"

params:
  term: "202580"
  id_column: "ID"

